apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: NodePort  
  selector:
    app: nginx-pod
  ports:
  - port: 80 #porta que fala com pod
    nodePort: 30000 # porta que falamos com o node
