apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  selector:
    app: sistema-noticias # app[sistema-noticias]----> svc[sistema-noticas]<----[cliente]
  ports:
  - port: 80
    nodePort: 30001
