apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec: #especificação do pod 
      containers:
        - name: portal-noticias-ctn
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  selector: #precisamos informar isso para selecionar os pods que vamos replicar 
     matchLabels: # para informar o kubernetes para gerenciar esse template
      app: portal-noticias 
