apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort  
  selector:
    app: portal-noticias
  ports:
  - port: 80 #porta que fala com pod
    nodePort: 30000 # porta que falamos com o node
